apiVersion: "execution.securecodebox.io/v1"
kind: Scan
metadata:
  name: "semgrep-vulnerable-juice-shop"
spec:
  volumes:
    - name: test-dir
      emptyDir: {}
  volumeMounts:
    - mountPath: "/test/"
      name: test-dir
  scanType: "semgrep"
  parameters:
    - "-c"
    - "auto"
    - "/test/juice-shop"
  initContainers:
    - name: "provision-git"
      image: bitnami/git
      command:
        - git
        - clone
        - "https://github.com/bkimminich/juice-shop"
        - /test/juice-shop
      volumeMounts:
        - mountPath: "/test/"
          name: test-dir

